# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d5cd357b106d67b56e834abbb2dd5e81a4fd82c148b78b688498962a9141817797cbfc8e933618c9da00ecd90346c33165a47250b869017732b4a4f466654a6

test:
  secret_key_base: 371b44605feb09768768fc1a0b3f444a9ece412c6a72214dc7590dfaac88e2963444ba0f439757ceda707591d2dea25a2e89487b38725ccf3b1916f4d13ab8e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
